/*
 *  Universidad Politecnica de San Luis Potosi
 *  Programacion III java
 *  Programacion Orientada a Objetos
 */
package proyectovideojuego;

import javax.swing.JOptionPane;

/**
 *
 */
public class Ayuda extends javax.swing.JFrame 
{
    private final Jugador jugador;

    public Ayuda(Jugador jugador) {
        this.jugador = jugador;
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnRetrocede = new javax.swing.JButton();
        btnNada = new javax.swing.JButton();
        btnAvanza = new javax.swing.JButton();
        btnPregunta = new javax.swing.JButton();
        btnSorpresa = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Chalkduster", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Avanzas 2 casillas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("¡¡DIVIERTETE!!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 280, 40));

        jLabel2.setFont(new java.awt.Font("Chalkduster", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Retrocede 2 casillas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Chalkduster", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Casilla de pregunta");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Chalkduster", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Casilla recompenza");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Chalkduster", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("Casilla sin sorpresa");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, -1));

        btnRetrocede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sorpresa1.png"))); // NOI18N
        btnRetrocede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocedeActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetrocede, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, 50));

        btnNada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro1 - copia.png"))); // NOI18N
        btnNada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNadaActionPerformed(evt);
            }
        });
        jPanel1.add(btnNada, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        btnAvanza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tablero.png"))); // NOI18N
        btnAvanza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAvanza, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        btnPregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pregunta.png"))); // NOI18N
        btnPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreguntaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 60, 60));

        btnSorpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/premio.png"))); // NOI18N
        btnSorpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorpresaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSorpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        btnSalir.setBackground(new java.awt.Color(255, 255, 102));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 0, 0));
        btnSalir.setText("REGRESAR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 130, 50));

        jTextArea1.setBackground(new java.awt.Color(242, 242, 242));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\t\n                                   En este juego deberas tirar el dado\n                            para que te salga un numero que te llevara\n                   a una nueva casilla en la que podras encontrarte con \n                            diferentes sorpresas de las que se muestran:\n\t(Selecciona el icono para mayor informacion)");
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 450, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ayuda.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 720, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*se muestran mensajes al dar clic en cada boton, esto para facilitar la vision del jugador (y no saturar la ventana de informacion)*/
    private void btnRetrocedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocedeActionPerformed
        JOptionPane.showMessageDialog(this, "Al caer en esta casilla regresar 2 lugares \nque te retrasaran para llegar a la meta");
    }//GEN-LAST:event_btnRetrocedeActionPerformed

    private void btnAvanzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzaActionPerformed
        JOptionPane.showMessageDialog(this, "Al caer en esta casilla podras avanzar 2 \nlugares que te acercaran mas a la meta");
    }//GEN-LAST:event_btnAvanzaActionPerformed

    private void btnPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreguntaActionPerformed
        JOptionPane.showMessageDialog(this, "Al caer en esta casilla deberas contestar tres \nsencillas preguntas que te haran ganar puntos y que te pondran\n a prueba para ver que tanto conoces la lengua");
    }//GEN-LAST:event_btnPreguntaActionPerformed

    private void btnNadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNadaActionPerformed
        JOptionPane.showMessageDialog(this, "Al caer en esta casilla no obtendras nada pero \npodras seguir jugando ya que estas casillas te acercan mas \na la meta");
    }//GEN-LAST:event_btnNadaActionPerformed

    private void btnSorpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorpresaActionPerformed
        JOptionPane.showMessageDialog(this, "Al caer en esta casilla obtedras 5 puntos de regalo, \nesto podra ponerte en primer lugar");
    }//GEN-LAST:event_btnSorpresaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //mensaje de advertencia antes de cerrar la ventana
        JOptionPane.showMessageDialog(this, "...¡CUIDADO!...\n\nAl obtener mas de los puntos para llegar a la \ncasilla 25 te reiniciara el juego :( perderas tus puntos y \ncomenzaras desde la casilla 1 nuevamente");
        Menu pantalla= new Menu(jugador);
        this.dispose();
        pantalla.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            Jugador jugador = new Jugador();
                new Ayuda(jugador).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanza;
    private javax.swing.JButton btnNada;
    private javax.swing.JButton btnPregunta;
    private javax.swing.JButton btnRetrocede;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSorpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
