/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectolabo;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel;

/**
 *
 * @author 176453
 */
public class ProyectoProgra extends javax.swing.JFrame {

    Usuarios usuarios = new Usuarios();

    /**
     * Creates new form ProyectoProgra
     */
    public ProyectoProgra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaRegistroDeUsuarios = new javax.swing.JFrame();
        botonNuevoUsuario = new javax.swing.JButton();
        eliminarLabel = new javax.swing.JLabel();
        idEliminar = new javax.swing.JTextField();
        darDeBajaUsuario = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        idLabel = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        saldoLabel = new javax.swing.JLabel();
        listaIdScroll = new javax.swing.JScrollPane();
        listaId = new javax.swing.JList<>();
        listaUsuarioScroll = new javax.swing.JScrollPane();
        listaUsuario = new javax.swing.JList<>();
        listaSaldoScroll = new javax.swing.JScrollPane();
        listaSaldo = new javax.swing.JList<>();
        listadoDeUsuarioBotonSalir = new javax.swing.JButton();
        seleccionarusuario = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        Juego = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton4 = new javax.swing.JButton();
        usuarioBoton = new javax.swing.JButton();
        salirBoton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        VentanaRegistroDeUsuarios.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonNuevoUsuario.setText("+");
        botonNuevoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNuevoUsuarioMouseClicked(evt);
            }
        });

        eliminarLabel.setText("ELIMINAR");

        darDeBajaUsuario.setText("-");

        idLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idLabel.setText("ID");

        usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuario.setText("USUARIO");

        saldoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saldoLabel.setText("SALDO");

        listaIdScroll.setViewportView(listaId);

        listaUsuarioScroll.setViewportView(listaUsuario);

        listaSaldoScroll.setViewportView(listaSaldo);

        listadoDeUsuarioBotonSalir.setText("SALIR");
        listadoDeUsuarioBotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoDeUsuarioBotonSalirMouseClicked(evt);
            }
        });
        listadoDeUsuarioBotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoDeUsuarioBotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VentanaRegistroDeUsuariosLayout = new javax.swing.GroupLayout(VentanaRegistroDeUsuarios.getContentPane());
        VentanaRegistroDeUsuarios.getContentPane().setLayout(VentanaRegistroDeUsuariosLayout);
        VentanaRegistroDeUsuariosLayout.setHorizontalGroup(
            VentanaRegistroDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaRegistroDeUsuariosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(VentanaRegistroDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaRegistroDeUsuariosLayout.createSequentialGroup()
                        .addGroup(VentanaRegistroDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VentanaRegistroDeUsuariosLayout.createSequentialGroup()
                                .addComponent(botonNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eliminarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VentanaRegistroDeUsuariosLayout.createSequentialGroup()
                                .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(VentanaRegistroDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(listaUsuarioScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(VentanaRegistroDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(listaSaldoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(saldoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(123, 123, 123)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(darDeBajaUsuario))
                    .addGroup(VentanaRegistroDeUsuariosLayout.createSequentialGroup()
                        .addComponent(listaIdScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(listadoDeUsuarioBotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        VentanaRegistroDeUsuariosLayout.setVerticalGroup(
            VentanaRegistroDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaRegistroDeUsuariosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(VentanaRegistroDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(darDeBajaUsuario)
                    .addComponent(botonNuevoUsuario))
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaRegistroDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(VentanaRegistroDeUsuariosLayout.createSequentialGroup()
                        .addComponent(saldoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaSaldoScroll))
                    .addGroup(VentanaRegistroDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(VentanaRegistroDeUsuariosLayout.createSequentialGroup()
                            .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(listaUsuarioScroll))
                        .addGroup(VentanaRegistroDeUsuariosLayout.createSequentialGroup()
                            .addComponent(idLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(listaIdScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listadoDeUsuarioBotonSalir)
                .addContainerGap())
        );

        seleccionarusuario.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccionar al jugador");

        jButton2.setText("ACEPTAR");

        javax.swing.GroupLayout seleccionarusuarioLayout = new javax.swing.GroupLayout(seleccionarusuario.getContentPane());
        seleccionarusuario.getContentPane().setLayout(seleccionarusuarioLayout);
        seleccionarusuarioLayout.setHorizontalGroup(
            seleccionarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionarusuarioLayout.createSequentialGroup()
                .addGroup(seleccionarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seleccionarusuarioLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1))
                    .addGroup(seleccionarusuarioLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(seleccionarusuarioLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(14, 14, 14))
        );
        seleccionarusuarioLayout.setVerticalGroup(
            seleccionarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionarusuarioLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(seleccionarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seleccionarusuarioLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(seleccionarusuarioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addGap(0, 75, Short.MAX_VALUE))
        );

        Juego.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("JUEGO DE PREGUNTAS");

        jLabel4.setText("PREGUNTAS");

        jButton3.setText("A");

        jToggleButton1.setText("B");

        jButton4.setText("jButton4");

        javax.swing.GroupLayout JuegoLayout = new javax.swing.GroupLayout(Juego.getContentPane());
        Juego.getContentPane().setLayout(JuegoLayout);
        JuegoLayout.setHorizontalGroup(
            JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JuegoLayout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))))
            .addGroup(JuegoLayout.createSequentialGroup()
                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel2))
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JuegoLayout.setVerticalGroup(
            JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JuegoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usuarioBoton.setText("USUARIOS");
        usuarioBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioBotonMouseClicked(evt);
            }
        });
        usuarioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioBotonActionPerformed(evt);
            }
        });

        salirBoton.setText("SALIR");
        salirBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirBotonMouseClicked(evt);
            }
        });

        jButton1.setText("JUGADOR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salirBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usuarioBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usuarioBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salirBoton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBotonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirBotonMouseClicked

    private void usuarioBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioBotonMouseClicked
        // TODO add your handling code here:
        VentanaRegistroDeUsuarios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_usuarioBotonMouseClicked

    private void usuarioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioBotonActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        DefaultListModel users = new DefaultListModel();
        for (int i = 0; i < usuarios.size(); i++) {
            users.addElement(usuarios.get(i).getUser_name());
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void listadoDeUsuarioBotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoDeUsuarioBotonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listadoDeUsuarioBotonSalirActionPerformed

    private void listadoDeUsuarioBotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoDeUsuarioBotonSalirMouseClicked
        // TODO add your handling code here:
        VentanaRegistroDeUsuarios.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_listadoDeUsuarioBotonSalirMouseClicked

    private void botonNuevoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNuevoUsuarioMouseClicked
        // TODO add your handling code here:
        DefaultListModel nombres = new DefaultListModel();
        DefaultListModel ids = new DefaultListModel();
        DefaultListModel saldos = new DefaultListModel();

        usuarios.AgregarUsuario();

        for (int i = 0; i < usuarios.size(); i++) {
            Usuario t = usuarios.get(i);

            System.out.println(t.getUser_name());

            nombres.addElement(t.getUser_name());
            ids.addElement(t.getId());
            saldos.addElement(t.getSaldo());
        }

        listaId.setModel(ids);
        listaUsuario.setModel(nombres);
        listaSaldo.setModel(saldos);
    }//GEN-LAST:event_botonNuevoUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectoProgra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectoProgra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectoProgra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectoProgra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectoProgra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Juego;
    private javax.swing.JFrame VentanaRegistroDeUsuarios;
    private javax.swing.JButton botonNuevoUsuario;
    private javax.swing.JButton darDeBajaUsuario;
    private javax.swing.JLabel eliminarLabel;
    private javax.swing.JTextField idEliminar;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JList<String> listaId;
    private javax.swing.JScrollPane listaIdScroll;
    private javax.swing.JList<String> listaSaldo;
    private javax.swing.JScrollPane listaSaldoScroll;
    private javax.swing.JList<String> listaUsuario;
    private javax.swing.JScrollPane listaUsuarioScroll;
    private javax.swing.JButton listadoDeUsuarioBotonSalir;
    private javax.swing.JLabel saldoLabel;
    private javax.swing.JButton salirBoton;
    private javax.swing.JFrame seleccionarusuario;
    private javax.swing.JLabel usuario;
    private javax.swing.JButton usuarioBoton;
    // End of variables declaration//GEN-END:variables
}
