/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectolabo;

import java.util.ArrayList;
import java.util.concurrent.ThreadLocalRandom;
import java.util.stream.Collectors;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author 176453
 */
public class ProyectoProgra extends javax.swing.JFrame {

    Usuarios usuarios = new Usuarios();
    int preguntasRespuestas = 0;
    int respondido = 0;

    Preguntas preguntas = new Preguntas();

    Pregunta preguntaActual;
    Usuario usuarioSeleccionado;

    /**
     * Creates new form ProyectoProgra
     */
    public ProyectoProgra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaRegistroDeUsuarios = new javax.swing.JFrame();
        botonNuevoUsuario = new javax.swing.JButton();
        eliminarLabel = new javax.swing.JLabel();
        idEliminar = new javax.swing.JTextField();
        darDeBajaUsuario = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        idLabel = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        saldoLabel = new javax.swing.JLabel();
        listaIdScroll = new javax.swing.JScrollPane();
        listaId = new javax.swing.JList<>();
        listaUsuarioScroll = new javax.swing.JScrollPane();
        listaUsuario = new javax.swing.JList<>();
        listaSaldoScroll = new javax.swing.JScrollPane();
        listaSaldo = new javax.swing.JList<>();
        listadoDeUsuarioBotonSalir = new javax.swing.JButton();
        seleccionarusuario = new javax.swing.JFrame();
        seleccionarJugadorLabel = new javax.swing.JLabel();
        SeleccionarJugadorComboBox = new javax.swing.JComboBox<>();
        SeleccionarJugadorButton = new javax.swing.JButton();
        SeleccionarJugadorSep = new javax.swing.JSeparator();
        Juego = new javax.swing.JFrame();
        Titulo = new javax.swing.JLabel();
        Pregunta = new javax.swing.JTextField();
        ButtonA = new javax.swing.JButton();
        ButtonB = new javax.swing.JToggleButton();
        ButtonC = new javax.swing.JButton();
        ButtonD = new javax.swing.JButton();
        Respuesta1 = new javax.swing.JTextField();
        Respuesta2 = new javax.swing.JTextField();
        Respuesta3 = new javax.swing.JTextField();
        Respuesta4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NombreDelUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        SaldoDelUsuario = new javax.swing.JTextField();
        EstadoDeLaRespuesta = new javax.swing.JLabel();
        SiguientePregunta = new javax.swing.JButton();
        usuarioBoton = new javax.swing.JButton();
        salirBoton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        VentanaRegistroDeUsuarios.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        VentanaRegistroDeUsuarios.setMinimumSize(new java.awt.Dimension(730, 294));

        botonNuevoUsuario.setText("+");
        botonNuevoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNuevoUsuarioMouseClicked(evt);
            }
        });

        eliminarLabel.setText("ELIMINAR");

        darDeBajaUsuario.setText("-");
        darDeBajaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                darDeBajaUsuarioMouseClicked(evt);
            }
        });

        idLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idLabel.setText("ID");

        usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuario.setText("USUARIO");

        saldoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saldoLabel.setText("SALDO");

        listaIdScroll.setViewportView(listaId);

        listaUsuarioScroll.setViewportView(listaUsuario);

        listaSaldoScroll.setViewportView(listaSaldo);

        listadoDeUsuarioBotonSalir.setText("SALIR");
        listadoDeUsuarioBotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoDeUsuarioBotonSalirMouseClicked(evt);
            }
        });
        listadoDeUsuarioBotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoDeUsuarioBotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VentanaRegistroDeUsuariosLayout = new javax.swing.GroupLayout(VentanaRegistroDeUsuarios.getContentPane());
        VentanaRegistroDeUsuarios.getContentPane().setLayout(VentanaRegistroDeUsuariosLayout);
        VentanaRegistroDeUsuariosLayout.setHorizontalGroup(
            VentanaRegistroDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaRegistroDeUsuariosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(VentanaRegistroDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(listadoDeUsuarioBotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VentanaRegistroDeUsuariosLayout.createSequentialGroup()
                        .addGroup(VentanaRegistroDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listaIdScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addGroup(VentanaRegistroDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listaUsuarioScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                            .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VentanaRegistroDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(listaSaldoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(saldoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(VentanaRegistroDeUsuariosLayout.createSequentialGroup()
                        .addComponent(botonNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(darDeBajaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        VentanaRegistroDeUsuariosLayout.setVerticalGroup(
            VentanaRegistroDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaRegistroDeUsuariosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(VentanaRegistroDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNuevoUsuario)
                    .addComponent(darDeBajaUsuario))
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(VentanaRegistroDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaRegistroDeUsuariosLayout.createSequentialGroup()
                        .addComponent(idLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaIdScroll))
                    .addGroup(VentanaRegistroDeUsuariosLayout.createSequentialGroup()
                        .addComponent(saldoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaSaldoScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                    .addGroup(VentanaRegistroDeUsuariosLayout.createSequentialGroup()
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaUsuarioScroll)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listadoDeUsuarioBotonSalir)
                .addContainerGap())
        );

        seleccionarusuario.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        seleccionarusuario.setMinimumSize(new java.awt.Dimension(600, 85));

        seleccionarJugadorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seleccionarJugadorLabel.setText("Seleccionar al jugador");

        SeleccionarJugadorButton.setText("ACEPTAR");
        SeleccionarJugadorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeleccionarJugadorButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout seleccionarusuarioLayout = new javax.swing.GroupLayout(seleccionarusuario.getContentPane());
        seleccionarusuario.getContentPane().setLayout(seleccionarusuarioLayout);
        seleccionarusuarioLayout.setHorizontalGroup(
            seleccionarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionarusuarioLayout.createSequentialGroup()
                .addGroup(seleccionarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seleccionarusuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(seleccionarJugadorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(SeleccionarJugadorSep)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seleccionarusuarioLayout.createSequentialGroup()
                        .addComponent(SeleccionarJugadorComboBox, 0, 508, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SeleccionarJugadorButton)))
                .addContainerGap())
        );
        seleccionarusuarioLayout.setVerticalGroup(
            seleccionarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionarusuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seleccionarJugadorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeleccionarJugadorSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seleccionarusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeleccionarJugadorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeleccionarJugadorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Juego.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setText("JUEGO DE PREGUNTAS");

        ButtonA.setText("A");

        ButtonB.setText("B");

        ButtonC.setText("C");

        ButtonD.setText("D");

        Respuesta1.setText("jTextField2");
        Respuesta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Respuesta1MouseClicked(evt);
            }
        });

        Respuesta2.setText("jTextField2");
        Respuesta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Respuesta2MouseClicked(evt);
            }
        });

        Respuesta3.setText("jTextField2");
        Respuesta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Respuesta3MouseClicked(evt);
            }
        });
        Respuesta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Respuesta3ActionPerformed(evt);
            }
        });

        Respuesta4.setText("jTextField2");
        Respuesta4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Respuesta4MouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Usuario");

        NombreDelUsuario.setText("jTextField6");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Saldo");

        SaldoDelUsuario.setText("jTextField7");

        EstadoDeLaRespuesta.setText("Respuesta: ");

        SiguientePregunta.setText("Siguiente");
        SiguientePregunta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SiguientePreguntaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JuegoLayout = new javax.swing.GroupLayout(Juego.getContentPane());
        Juego.getContentPane().setLayout(JuegoLayout);
        JuegoLayout.setHorizontalGroup(
            JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pregunta)
                            .addGroup(JuegoLayout.createSequentialGroup()
                                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ButtonA, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                    .addComponent(ButtonB, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                    .addComponent(ButtonC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Respuesta4, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                                    .addComponent(Respuesta3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Respuesta2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Respuesta1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NombreDelUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SaldoDelUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(6, 6, 6))
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addComponent(EstadoDeLaRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(SiguientePregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        JuegoLayout.setVerticalGroup(
            JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonA)
                    .addComponent(Respuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonB)
                    .addComponent(Respuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreDelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonC)
                    .addComponent(Respuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonD)
                    .addComponent(Respuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaldoDelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EstadoDeLaRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SiguientePregunta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 93));

        usuarioBoton.setText("USUARIOS");
        usuarioBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioBotonMouseClicked(evt);
            }
        });
        usuarioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioBotonActionPerformed(evt);
            }
        });

        salirBoton.setText("SALIR");
        salirBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirBotonMouseClicked(evt);
            }
        });

        jButton1.setText("JUGADOR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salirBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usuarioBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usuarioBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salirBoton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBotonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirBotonMouseClicked

    private void usuarioBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioBotonMouseClicked
        // TODO add your handling code here:
        VentanaRegistroDeUsuarios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_usuarioBotonMouseClicked

    private void usuarioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioBotonActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

        Object[] users = new Object[usuarios.size()];
        for (int i = 0; i < usuarios.size(); i++) {
            users[i] = usuarios.get(i).getUser_name();
        }
        ComboBoxModel comboBoxModel = new DefaultComboBoxModel(users);

        SeleccionarJugadorComboBox.setModel(comboBoxModel);

        this.setVisible(false);
        seleccionarusuario.setVisible(true);

    }//GEN-LAST:event_jButton1MouseClicked

    private void listadoDeUsuarioBotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoDeUsuarioBotonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listadoDeUsuarioBotonSalirActionPerformed

    private void listadoDeUsuarioBotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoDeUsuarioBotonSalirMouseClicked
        // TODO add your handling code here:
        VentanaRegistroDeUsuarios.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_listadoDeUsuarioBotonSalirMouseClicked

    private void botonNuevoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNuevoUsuarioMouseClicked
        // TODO add your handling code here:
        DefaultListModel nombres = new DefaultListModel();
        DefaultListModel ids = new DefaultListModel();
        DefaultListModel saldos = new DefaultListModel();

        usuarios.AgregarUsuario();

        for (int i = 0; i < usuarios.size(); i++) {
            Usuario t = usuarios.get(i);

            System.out.println(t.getUser_name());

            nombres.addElement(t.getUser_name());
            ids.addElement(t.getId());
            saldos.addElement(t.getSaldo());
        }

        System.out.println("---");

        listaId.setModel(ids);
        listaUsuario.setModel(nombres);
        listaSaldo.setModel(saldos);
    }//GEN-LAST:event_botonNuevoUsuarioMouseClicked

    private void darDeBajaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_darDeBajaUsuarioMouseClicked
        // TODO add your handling code here:

        if (idEliminar.getText().isBlank() || idEliminar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Porfavor, introduce un usuario");
            return;
        }

        int id_a_eliminar = Integer.parseInt(idEliminar.getText());
        Usuario a_eliminar = usuarios.getById(id_a_eliminar);
        Double saldo_a_repartir = 0.0;

        if (a_eliminar == null) {
            JOptionPane.showMessageDialog(rootPane, "El usuario no existe");
            return;
        } else {
            saldo_a_repartir = a_eliminar.getSaldo();
        }

        usuarios.eliminarUsuario(id_a_eliminar);

        Usuario usuario_con_menor_saldo = usuarios.get(0);
        Double menor_saldo = usuario_con_menor_saldo.getSaldo();
        for (int i = 0; i < usuarios.size(); i++) {
            if (usuarios.get(i).getSaldo() < menor_saldo) {
                usuario_con_menor_saldo = usuarios.get(i);
                menor_saldo = usuario_con_menor_saldo.getSaldo();
            }
        }

        if (usuario_con_menor_saldo == null) {
            return;
        }

        usuario_con_menor_saldo.setSaldo(usuario_con_menor_saldo.getSaldo() + (saldo_a_repartir * 0.1));
        usuarios.replaceUser(usuario_con_menor_saldo.getId(), usuario_con_menor_saldo);
        usuarios.remove(a_eliminar);

        DefaultListModel nombres = new DefaultListModel();
        DefaultListModel ids = new DefaultListModel();
        DefaultListModel saldos = new DefaultListModel();

        for (int i = 0; i < usuarios.size(); i++) {
            Usuario t = usuarios.get(i);

            System.out.println(t.getUser_name());

            nombres.addElement(t.getUser_name());
            ids.addElement(t.getId());
            saldos.addElement(t.getSaldo());
        }

        System.out.println("---");

        listaId.removeAll();
        listaUsuario.removeAll();
        listaSaldo.removeAll();

        listaId.setModel(ids);
        listaUsuario.setModel(nombres);
        listaSaldo.setModel(saldos);

    }//GEN-LAST:event_darDeBajaUsuarioMouseClicked

    private void Respuesta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Respuesta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Respuesta3ActionPerformed

    public void ponerPregunta() {
        Pregunta.setText(preguntaActual.titulo);
        Respuesta1.setText(preguntaActual.opciones[0]);
        Respuesta2.setText(preguntaActual.opciones[1]);
        Respuesta3.setText(preguntaActual.opciones[2]);
        Respuesta4.setText(preguntaActual.opciones[3]);
        EstadoDeLaRespuesta.setText("Respuesta: ");

        Respuesta1.setEnabled(true);
        Respuesta2.setEnabled(true);
        Respuesta3.setEnabled(true);
        Respuesta4.setEnabled(true);
        SiguientePregunta.setEnabled(false);

        NombreDelUsuario.setText(usuarioSeleccionado.getUser_name());
        SaldoDelUsuario.setText(String.valueOf(usuarioSeleccionado.getSaldo()));
    }

    public void checarPregunta() {
        Respuesta1.setEnabled(false);
        Respuesta2.setEnabled(false);
        Respuesta3.setEnabled(false);
        Respuesta4.setEnabled(false);

        SiguientePregunta.setEnabled(true);
        preguntasRespuestas += 1;

        if (respondido == preguntaActual.opcion_correcta) {
            usuarioSeleccionado.setSaldo(usuarioSeleccionado.getSaldo() + 50);
            EstadoDeLaRespuesta.setText("Respuesta: CORRECTA");
        } else {
            usuarioSeleccionado.setSaldo(usuarioSeleccionado.getSaldo() - 60);
            EstadoDeLaRespuesta.setText("Respuesta: INCORRECTA");

        }

    }

    private void SeleccionarJugadorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeleccionarJugadorButtonMouseClicked
        // TODO add your handling code here:

        // Usuario seleccionado
        String nombre_de_usuario_seleccionado = SeleccionarJugadorComboBox.getSelectedItem().toString();
        Usuario usuario_seleccionado = usuarios.get(nombre_de_usuario_seleccionado);

        preguntasRespuestas = 0;
        preguntas.setPreguntas();

        Pregunta pregunta = preguntas.get(ThreadLocalRandom.current().nextInt(0, preguntas.size()) + 1);

        usuarioSeleccionado = usuario_seleccionado;
        preguntaActual = pregunta;

        ponerPregunta();

        seleccionarusuario.setVisible(false);
        Juego.setVisible(true);
    }//GEN-LAST:event_SeleccionarJugadorButtonMouseClicked

    private void Respuesta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Respuesta1MouseClicked
        // TODO add your handling code here:
        respondido = 0;
        checarPregunta();
    }//GEN-LAST:event_Respuesta1MouseClicked

    private void Respuesta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Respuesta2MouseClicked
        // TODO add your handling code here:
        respondido = 1;
        checarPregunta();

    }//GEN-LAST:event_Respuesta2MouseClicked

    private void Respuesta3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Respuesta3MouseClicked
        // TODO add your handling code here:
        respondido = 2;
        checarPregunta();

    }//GEN-LAST:event_Respuesta3MouseClicked

    private void Respuesta4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Respuesta4MouseClicked
        // TODO add your handling code here:
        respondido = 3;
        checarPregunta();

    }//GEN-LAST:event_Respuesta4MouseClicked

    private void SiguientePreguntaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SiguientePreguntaMouseClicked
        // TODO add your handling code here:
        if (preguntasRespuestas < 10) {
            Pregunta pregunta = preguntas.get(ThreadLocalRandom.current().nextInt(0, preguntas.size()) + 1);
            preguntaActual = pregunta;
            ponerPregunta();
        } else {
            usuarios.replaceUser(usuarioSeleccionado.getId(), usuarioSeleccionado);
            JOptionPane.showMessageDialog(rootPane, "JUEGO TERMINADO: " + usuarioSeleccionado.getUser_name() + ", terminaste con un saldo de: " + usuarioSeleccionado.getSaldo());

            this.setVisible(true);
            Juego.setVisible(false);
        }
    }//GEN-LAST:event_SiguientePreguntaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectoProgra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectoProgra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectoProgra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectoProgra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectoProgra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonA;
    private javax.swing.JToggleButton ButtonB;
    private javax.swing.JButton ButtonC;
    private javax.swing.JButton ButtonD;
    private javax.swing.JLabel EstadoDeLaRespuesta;
    private javax.swing.JFrame Juego;
    private javax.swing.JTextField NombreDelUsuario;
    private javax.swing.JTextField Pregunta;
    private javax.swing.JTextField Respuesta1;
    private javax.swing.JTextField Respuesta2;
    private javax.swing.JTextField Respuesta3;
    private javax.swing.JTextField Respuesta4;
    private javax.swing.JTextField SaldoDelUsuario;
    private javax.swing.JButton SeleccionarJugadorButton;
    private javax.swing.JComboBox<String> SeleccionarJugadorComboBox;
    private javax.swing.JSeparator SeleccionarJugadorSep;
    private javax.swing.JButton SiguientePregunta;
    private javax.swing.JLabel Titulo;
    private javax.swing.JFrame VentanaRegistroDeUsuarios;
    private javax.swing.JButton botonNuevoUsuario;
    private javax.swing.JButton darDeBajaUsuario;
    private javax.swing.JLabel eliminarLabel;
    private javax.swing.JTextField idEliminar;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> listaId;
    private javax.swing.JScrollPane listaIdScroll;
    private javax.swing.JList<String> listaSaldo;
    private javax.swing.JScrollPane listaSaldoScroll;
    private javax.swing.JList<String> listaUsuario;
    private javax.swing.JScrollPane listaUsuarioScroll;
    private javax.swing.JButton listadoDeUsuarioBotonSalir;
    private javax.swing.JLabel saldoLabel;
    private javax.swing.JButton salirBoton;
    private javax.swing.JLabel seleccionarJugadorLabel;
    private javax.swing.JFrame seleccionarusuario;
    private javax.swing.JLabel usuario;
    private javax.swing.JButton usuarioBoton;
    // End of variables declaration//GEN-END:variables
}
