/*
 * 177847 Alfredo De Alba Sánchez;
 * Programacion III;
 */
package proyecto_final_jap;
import javax.swing.JOptionPane;

/**
 *
 * @author licbe
 */

public class Main extends javax.swing.JFrame 
{

    public Main() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        jLabel1 = new javax.swing.JLabel();
        Idioma = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Juego_1 = new javax.swing.JButton();
        Dificultad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Juego_2 = new javax.swing.JButton();
        Juego_3 = new javax.swing.JButton();
        Juego_4 = new javax.swing.JButton();
        Juego_5 = new javax.swing.JButton();
        Juego_6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccionar Juego");

        Idioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Náhuatl", "Huasteco",}));

        jLabel2.setText("Lenguaje");

        Juego_1.setText("Jared1");
        Juego_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Juego_1MouseClicked(evt);
            }
        });
        Juego_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Juego_1ActionPerformed(evt);
            }
        });

        Dificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dificil","Facil"}));

        jLabel3.setText("Dificultad");

        Juego_2.setText("Jared2");
        Juego_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Juego_2MouseClicked(evt);
            }
        });

        Juego_3.setText("Alan1");

        Juego_4.setText("Alan2");

        Juego_5.setText("Juan1");

        Juego_6.setText("Juan2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Dificultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Juego_1)
                    .addComponent(Juego_5)
                    .addComponent(Juego_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Juego_2)
                    .addComponent(Juego_4)
                    .addComponent(Juego_6))
                .addGap(161, 161, 161))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Juego_1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(Juego_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Juego_4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Juego_3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Juego_6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Juego_5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dificultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Juego_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Juego_1MouseClicked
        // TODO add your handling code here:
        
        String dif,idi;
        idi=Idioma.getSelectedItem().toString();
        dif=Dificultad.getSelectedItem().toString();
        JOptionPane.showConfirmDialog(this, "Juego_1\n Idioma:"+idi+"\nDificultad:"+dif);
        
      // if()
        {
        
        }
    }//GEN-LAST:event_Juego_1MouseClicked

    private void Juego_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Juego_2MouseClicked
        
        String dif,idi;
        idi=Idioma.getSelectedItem().toString();
        dif=Dificultad.getSelectedItem().toString();
        JOptionPane.showConfirmDialog(this, "Juego_2\n Idioma:"+idi+"\nDificultad:"+dif);
        
    }//GEN-LAST:event_Juego_2MouseClicked

    private void Juego_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Juego_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Juego_1ActionPerformed

    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Dificultad;
    private javax.swing.JComboBox<String> Idioma;
    private javax.swing.JButton Juego_1;
    private javax.swing.JButton Juego_2;
    private javax.swing.JButton Juego_3;
    private javax.swing.JButton Juego_4;
    private javax.swing.JButton Juego_5;
    private javax.swing.JButton Juego_6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends javax.swing.JPanel
    {
        private java.awt.Image imagen;
        @Override
        public void paint(java.awt.Graphics g){
            //imagen = new javax.swing.ImageIcon(getClass().getResource("/imagenes/Portada.jpg")).getImage();
            
            g.drawImage(imagen, 0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }

}
