/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboproyecto;

import javax.swing.UIManager;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author 177685
 */
public class Proyecto extends javax.swing.JFrame {

    Usuarios usuarios;
    Usuario usuario_seleccionado;

    /**
     * Creates new form Proyecto
     */
    public Proyecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsuariosFrame = new javax.swing.JFrame();
        Agregar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        TablaScroll = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Regresar = new javax.swing.JButton();
        Id = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Seleccionador = new javax.swing.JFrame();
        SeleccionarJugadorLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        SeleccionarJugadorComboBox = new javax.swing.JComboBox<>();
        SeleccionarJugadorBoton = new javax.swing.JButton();
        Juego = new javax.swing.JFrame();
        TituloDeLaVentana = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        TituloDeLaPregunta = new javax.swing.JLabel();
        JugadorLabel = new javax.swing.JLabel();
        SaldoLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        Respuesta1 = new javax.swing.JButton();
        Respuesta2 = new javax.swing.JButton();
        Respuesta3 = new javax.swing.JButton();
        Respuesta4 = new javax.swing.JButton();
        Responder = new javax.swing.JButton();
        SiguientePregunta = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        Usuarios = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Jugar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        UsuariosFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        UsuariosFrame.setTitle("Usuarios");
        UsuariosFrame.setMinimumSize(new java.awt.Dimension(549, 345));
        UsuariosFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                UsuariosFrameWindowClosing(evt);
            }
        });

        Agregar.setText("Agregar");
        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarMouseClicked(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.setToolTipText("");
        TablaScroll.setViewportView(Tabla);

        Regresar.setText("Regresar");
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
        });

        Id.setForeground(java.awt.Color.gray);
        Id.setText("Introduce el ID");
        Id.setToolTipText("Introduce el ID");
        Id.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Id.setName("Introduce el ID"); // NOI18N
        Id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IdFocusLost(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout UsuariosFrameLayout = new javax.swing.GroupLayout(UsuariosFrame.getContentPane());
        UsuariosFrame.getContentPane().setLayout(UsuariosFrameLayout);
        UsuariosFrameLayout.setHorizontalGroup(
            UsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuariosFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TablaScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addGroup(UsuariosFrameLayout.createSequentialGroup()
                        .addComponent(Agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eliminar))
                    .addGroup(UsuariosFrameLayout.createSequentialGroup()
                        .addComponent(Regresar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        UsuariosFrameLayout.setVerticalGroup(
            UsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsuariosFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Agregar)
                        .addComponent(Eliminar)
                        .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TablaScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Regresar)
                .addContainerGap())
        );

        Id.getAccessibleContext().setAccessibleName("Introduce el ID");

        Seleccionador.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        Seleccionador.setTitle("Selecciona tu Usuario");
        Seleccionador.setMinimumSize(new java.awt.Dimension(500, 120));
        Seleccionador.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                SeleccionadorWindowClosing(evt);
            }
        });

        SeleccionarJugadorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SeleccionarJugadorLabel.setText("Selecciona el usuario con el que quieres jugar");

        SeleccionarJugadorBoton.setText("Seleccionar");
        SeleccionarJugadorBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeleccionarJugadorBotonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SeleccionadorLayout = new javax.swing.GroupLayout(Seleccionador.getContentPane());
        Seleccionador.getContentPane().setLayout(SeleccionadorLayout);
        SeleccionadorLayout.setHorizontalGroup(
            SeleccionadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeleccionadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SeleccionadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeleccionarJugadorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addGroup(SeleccionadorLayout.createSequentialGroup()
                        .addComponent(SeleccionarJugadorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SeleccionarJugadorBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SeleccionadorLayout.setVerticalGroup(
            SeleccionadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeleccionadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SeleccionarJugadorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SeleccionadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeleccionarJugadorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeleccionarJugadorBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Juego.setTitle("Juego de Preguntas y Respuestas");

        TituloDeLaVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloDeLaVentana.setText("Juego de Preguntas y Respuestas");

        TituloDeLaPregunta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloDeLaPregunta.setText("<Titulo>");

        JugadorLabel.setText("Usuario: <Nombre de Usuario>");

        SaldoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SaldoLabel.setText("Saldo: $<Saldo>");

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Respuesta1.setText("<Respuesta 1>");

        Respuesta2.setText("<Respuesta 2>");

        Respuesta3.setText("<Respuesta 3>");

        Respuesta4.setText("<Respuesta 4>");

        Responder.setText("Responder");

        SiguientePregunta.setText("Siguiente Pregunta");

        javax.swing.GroupLayout JuegoLayout = new javax.swing.GroupLayout(Juego.getContentPane());
        Juego.getContentPane().setLayout(JuegoLayout);
        JuegoLayout.setHorizontalGroup(
            JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JuegoLayout.createSequentialGroup()
                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloDeLaVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4)))
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(TituloDeLaPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JugadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaldoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Respuesta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Respuesta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Respuesta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Respuesta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Responder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JuegoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SiguientePregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator6)))
                .addContainerGap())
        );
        JuegoLayout.setVerticalGroup(
            JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloDeLaVentana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JugadorLabel)
                        .addComponent(SaldoLabel))
                    .addComponent(jSeparator5))
                .addGap(18, 18, 18)
                .addComponent(TituloDeLaPregunta)
                .addGap(18, 18, 18)
                .addComponent(Respuesta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Respuesta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Respuesta3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Respuesta4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Responder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SiguientePregunta)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Usuarios.setText("USUARIOS");
        Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuariosMouseClicked(evt);
            }
        });

        Salir.setText("SALIR");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });

        Jugar.setText("JUGAR");
        Jugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JugarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addComponent(Usuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(Salir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jugar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Usuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jugar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuariosMouseClicked
        // TODO add your handling code here:
        UsuariosFrame.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_UsuariosMouseClicked

    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        // TODO add your handling code here:
        this.setVisible(true);
        UsuariosFrame.setVisible(false);
    }//GEN-LAST:event_RegresarMouseClicked

    private void IdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IdFocusGained
        // TODO add your handling code here:
        if (Id.getText().equals("Introduce el ID")) {
            Id.setForeground(Color.BLACK);
            Id.setText("");
        }
    }//GEN-LAST:event_IdFocusGained

    private void IdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IdFocusLost
        // TODO add your handling code here:
        if (Id.getText().isEmpty()) {
            Id.setForeground(Color.GRAY);
            Id.setText("Introduce el ID");
        }
    }//GEN-LAST:event_IdFocusLost

    private void AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseClicked
        // TODO add your handling code here:
        usuarios.addUser();
        Tabla.setModel(usuarios.toTableModel());
    }//GEN-LAST:event_AgregarMouseClicked

    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseClicked
        // TODO add your handling code here:
        if (Id.getText().isBlank() || Id.getText().isEmpty()) {
            return;
        }

        int id = Integer.parseInt(Id.getText());
        if (!usuarios.deleteUser(id)) {
            JOptionPane.showMessageDialog(rootPane, "El usuario no existe o sucedió un error no-fatal.");
        }

        Tabla.setModel(usuarios.toTableModel());
    }//GEN-LAST:event_EliminarMouseClicked

    private void JugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JugarMouseClicked
        // TODO add your handling code here:}
        if (usuarios.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Sin usuarios por seleccionar");
            return;
        }

        this.setVisible(false);

        SeleccionarJugadorComboBox.setModel(usuarios.toComboBoxModel());
        SeleccionarJugadorComboBox.setSelectedIndex(0);

        Seleccionador.setVisible(true);
    }//GEN-LAST:event_JugarMouseClicked

    private void SeleccionadorWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_SeleccionadorWindowClosing
        // TODO add your handling code here:
        this.setVisible(true);
        Seleccionador.setVisible(false);
    }//GEN-LAST:event_SeleccionadorWindowClosing

    private void UsuariosFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_UsuariosFrameWindowClosing
        // TODO add your handling code here:
        this.setVisible((true));
        UsuariosFrame.setVisible(false);
    }//GEN-LAST:event_UsuariosFrameWindowClosing

    private void setPreguntaIntoForm() {
        JugadorLabel.setText("Usuario: " + usuario_seleccionado.getUserName());
        SaldoLabel.setText("Saldo: $" + usuario_seleccionado.getSaldo());
        
    }

    private void SeleccionarJugadorBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeleccionarJugadorBotonMouseClicked
        // TODO add your handling code here:
        Seleccionador.setVisible(false);

        // Start Game
        usuario_seleccionado = (Usuario) SeleccionarJugadorComboBox.getSelectedItem();
        setPreguntaIntoForm();

        Juego.setVisible(true);
    }//GEN-LAST:event_SeleccionarJugadorBotonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF: " + ex);

            try {
                FlatLightLaf.setup();
            } catch (Exception ex2) {
                System.err.println("Failed to initialize LaF: " + ex2);
            }
        }

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */ /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField Id;
    private javax.swing.JFrame Juego;
    private javax.swing.JLabel JugadorLabel;
    private javax.swing.JButton Jugar;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton Responder;
    private javax.swing.JButton Respuesta1;
    private javax.swing.JButton Respuesta2;
    private javax.swing.JButton Respuesta3;
    private javax.swing.JButton Respuesta4;
    private javax.swing.JLabel SaldoLabel;
    private javax.swing.JButton Salir;
    private javax.swing.JFrame Seleccionador;
    private javax.swing.JButton SeleccionarJugadorBoton;
    private javax.swing.JComboBox<String> SeleccionarJugadorComboBox;
    private javax.swing.JLabel SeleccionarJugadorLabel;
    private javax.swing.JButton SiguientePregunta;
    private javax.swing.JTable Tabla;
    private javax.swing.JScrollPane TablaScroll;
    private javax.swing.JLabel TituloDeLaPregunta;
    private javax.swing.JLabel TituloDeLaVentana;
    private javax.swing.JButton Usuarios;
    private javax.swing.JFrame UsuariosFrame;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
