/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboproyecto;

import javax.swing.UIManager;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author 177685
 */
public class Proyecto extends javax.swing.JFrame {
    
    Usuarios usuarios = new Usuarios();
    Usuario usuario_seleccionado;
    int opcion_seleccionada;
    
    Preguntas preguntas = new Preguntas();
    Pregunta pregunta_seleccionada;

    /**
     * Creates new form Proyecto
     */
    public Proyecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsuariosFrame = new javax.swing.JFrame();
        Agregar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        TablaScroll = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Regresar = new javax.swing.JButton();
        Id = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Seleccionador = new javax.swing.JFrame();
        SeleccionarJugadorLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        SeleccionarJugadorComboBox = new javax.swing.JComboBox<>();
        SeleccionarJugadorBoton = new javax.swing.JButton();
        Juego = new javax.swing.JFrame();
        TituloDeLaVentana = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        TituloDeLaPregunta = new javax.swing.JLabel();
        JugadorLabel = new javax.swing.JLabel();
        SaldoLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        Respuesta1 = new javax.swing.JButton();
        Respuesta2 = new javax.swing.JButton();
        Respuesta3 = new javax.swing.JButton();
        Respuesta4 = new javax.swing.JButton();
        SiguientePregunta = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        ResultadoDeLaPregunta = new javax.swing.JLabel();
        Usuarios = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Jugar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        UsuariosFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        UsuariosFrame.setTitle("Usuarios");
        UsuariosFrame.setMinimumSize(new java.awt.Dimension(549, 345));
        UsuariosFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                UsuariosFrameWindowClosing(evt);
            }
        });

        Agregar.setText("Agregar");
        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarMouseClicked(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.setToolTipText("");
        TablaScroll.setViewportView(Tabla);

        Regresar.setText("Regresar");
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
        });

        Id.setForeground(java.awt.Color.gray);
        Id.setText("Introduce el ID");
        Id.setToolTipText("Introduce el ID");
        Id.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Id.setName("Introduce el ID"); // NOI18N
        Id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IdFocusLost(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout UsuariosFrameLayout = new javax.swing.GroupLayout(UsuariosFrame.getContentPane());
        UsuariosFrame.getContentPane().setLayout(UsuariosFrameLayout);
        UsuariosFrameLayout.setHorizontalGroup(
            UsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuariosFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TablaScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addGroup(UsuariosFrameLayout.createSequentialGroup()
                        .addComponent(Agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eliminar))
                    .addGroup(UsuariosFrameLayout.createSequentialGroup()
                        .addComponent(Regresar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        UsuariosFrameLayout.setVerticalGroup(
            UsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsuariosFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UsuariosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Agregar)
                        .addComponent(Eliminar)
                        .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TablaScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Regresar)
                .addContainerGap())
        );

        Id.getAccessibleContext().setAccessibleName("Introduce el ID");

        Seleccionador.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        Seleccionador.setTitle("Selecciona tu Usuario");
        Seleccionador.setMinimumSize(new java.awt.Dimension(500, 120));
        Seleccionador.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                SeleccionadorWindowClosing(evt);
            }
        });

        SeleccionarJugadorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SeleccionarJugadorLabel.setText("Selecciona el usuario con el que quieres jugar");

        SeleccionarJugadorBoton.setText("Seleccionar");
        SeleccionarJugadorBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeleccionarJugadorBotonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SeleccionadorLayout = new javax.swing.GroupLayout(Seleccionador.getContentPane());
        Seleccionador.getContentPane().setLayout(SeleccionadorLayout);
        SeleccionadorLayout.setHorizontalGroup(
            SeleccionadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeleccionadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SeleccionadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeleccionarJugadorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addGroup(SeleccionadorLayout.createSequentialGroup()
                        .addComponent(SeleccionarJugadorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SeleccionarJugadorBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SeleccionadorLayout.setVerticalGroup(
            SeleccionadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeleccionadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SeleccionarJugadorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SeleccionadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeleccionarJugadorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeleccionarJugadorBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Juego.setTitle("Juego de Preguntas y Respuestas");

        TituloDeLaVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloDeLaVentana.setText("Juego de Preguntas y Respuestas");

        TituloDeLaPregunta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloDeLaPregunta.setText("<Titulo>");

        JugadorLabel.setText("Usuario: <Nombre de Usuario>");

        SaldoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SaldoLabel.setText("Saldo: $<Saldo>");

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Respuesta1.setText("<Respuesta 1>");
        Respuesta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Respuesta1MouseClicked(evt);
            }
        });

        Respuesta2.setText("<Respuesta 2>");
        Respuesta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Respuesta2MouseClicked(evt);
            }
        });

        Respuesta3.setText("<Respuesta 3>");
        Respuesta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Respuesta3MouseClicked(evt);
            }
        });

        Respuesta4.setText("<Respuesta 4>");
        Respuesta4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Respuesta4MouseClicked(evt);
            }
        });

        SiguientePregunta.setText("Siguiente Pregunta");
        SiguientePregunta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SiguientePreguntaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JuegoLayout = new javax.swing.GroupLayout(Juego.getContentPane());
        Juego.getContentPane().setLayout(JuegoLayout);
        JuegoLayout.setHorizontalGroup(
            JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JuegoLayout.createSequentialGroup()
                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloDeLaVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4)))
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(TituloDeLaPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JugadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaldoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Respuesta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Respuesta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Respuesta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Respuesta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JuegoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ResultadoDeLaPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SiguientePregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JuegoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator6)))
                .addContainerGap())
        );
        JuegoLayout.setVerticalGroup(
            JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloDeLaVentana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JugadorLabel)
                        .addComponent(SaldoLabel))
                    .addComponent(jSeparator5))
                .addGap(18, 18, 18)
                .addComponent(TituloDeLaPregunta)
                .addGap(18, 18, 18)
                .addComponent(Respuesta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Respuesta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Respuesta3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Respuesta4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiguientePregunta)
                    .addComponent(ResultadoDeLaPregunta))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Usuarios.setText("USUARIOS");
        Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuariosMouseClicked(evt);
            }
        });

        Salir.setText("SALIR");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });

        Jugar.setText("JUGAR");
        Jugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JugarMouseClicked(evt);
            }
        });
        Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addComponent(Usuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(Salir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jugar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Usuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jugar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuariosMouseClicked
        // TODO add your handling code here:
        UsuariosFrame.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_UsuariosMouseClicked

    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        // TODO add your handling code here:
        this.setVisible(true);
        UsuariosFrame.setVisible(false);
    }//GEN-LAST:event_RegresarMouseClicked

    private void IdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IdFocusGained
        // TODO add your handling code here:
        if (Id.getText().equals("Introduce el ID")) {
            Id.setForeground(Color.BLACK);
            Id.setText("");
        }
    }//GEN-LAST:event_IdFocusGained

    private void IdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IdFocusLost
        // TODO add your handling code here:
        if (Id.getText().isEmpty()) {
            Id.setForeground(Color.GRAY);
            Id.setText("Introduce el ID");
        }
    }//GEN-LAST:event_IdFocusLost

    private void AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseClicked
        // TODO add your handling code here:
        usuarios.addUser();
        Tabla.setModel(usuarios.toTableModel());
    }//GEN-LAST:event_AgregarMouseClicked

    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseClicked
        // TODO add your handling code here:
        if (Id.getText().isBlank() || Id.getText().isEmpty()) {
            return;
        }
        
        int id = Integer.parseInt(Id.getText());
        if (!usuarios.deleteUser(id)) {
            JOptionPane.showMessageDialog(rootPane, "El usuario no existe o sucedió un error no-fatal.");
        }
        
        Tabla.setModel(usuarios.toTableModel());
    }//GEN-LAST:event_EliminarMouseClicked

    private void JugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JugarMouseClicked
        // TODO add your handling code here:}
        if (usuarios.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Sin usuarios por seleccionar");
            return;
        }
        
        this.setVisible(false);
        
        SeleccionarJugadorComboBox.setModel(usuarios.toComboBoxModel());
        SeleccionarJugadorComboBox.setSelectedIndex(0);
        
        Seleccionador.setVisible(true);
    }//GEN-LAST:event_JugarMouseClicked

    private void SeleccionadorWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_SeleccionadorWindowClosing
        // TODO add your handling code here:
        this.setVisible(true);
        Seleccionador.setVisible(false);
    }//GEN-LAST:event_SeleccionadorWindowClosing

    private void UsuariosFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_UsuariosFrameWindowClosing
        // TODO add your handling code here:
        this.setVisible((true));
        UsuariosFrame.setVisible(false);
    }//GEN-LAST:event_UsuariosFrameWindowClosing
    
    private void setPreguntaIntoForm() {
        JugadorLabel.setText("Usuario: " + usuario_seleccionado.getUserName());
        SaldoLabel.setText("Saldo: $" + usuario_seleccionado.getSaldo());
        
        Pregunta pregunta_actual = preguntas.getPregunta();
        pregunta_seleccionada = pregunta_actual;
        
        TituloDeLaPregunta.setText(pregunta_actual.getPregunta());
        Respuesta1.setText(pregunta_actual.getOpciones().get(0));
        Respuesta2.setText(pregunta_actual.getOpciones().get(1));
        Respuesta3.setText(pregunta_actual.getOpciones().get(2));
        Respuesta4.setText(pregunta_actual.getOpciones().get(3));
        
        Respuesta1.setEnabled(true);
        Respuesta2.setEnabled(true);
        Respuesta3.setEnabled(true);
        Respuesta4.setEnabled(true);
        
        SiguientePregunta.setEnabled(false);
        ResultadoDeLaPregunta.setText("");
    }
    
    public void checar() {
        if (opcion_seleccionada == pregunta_seleccionada.getIndexRespuestaCorrecta()) {
            usuario_seleccionado.setSaldo(usuario_seleccionado.getSaldo() + 50.0);
            ResultadoDeLaPregunta.setText("Correcto");
        } else {
            usuario_seleccionado.setSaldo(usuario_seleccionado.getSaldo() - 60.0);
            ResultadoDeLaPregunta.setText("Incorrecto");
        }
        
        Respuesta1.setEnabled(false);
        Respuesta2.setEnabled(false);
        Respuesta3.setEnabled(false);
        Respuesta4.setEnabled(false);
        SiguientePregunta.setEnabled(true);
    }

    private void SeleccionarJugadorBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeleccionarJugadorBotonMouseClicked
        // TODO add your handling code here:
        Seleccionador.setVisible(false);

        // Start Game
        usuario_seleccionado = usuarios.getUser(SeleccionarJugadorComboBox.getSelectedIndex());

        // Add preguntas
        preguntas.addPregunta("¿Cuál es la capital de México?", 0, new ArrayList<>(List.of("Ciudad de México", "Guadalajara", "Monterrey", "Cancún")));
        preguntas.addPregunta("¿Cuál es el río más largo del mundo?", 1, new ArrayList<>(List.of("Río Amazonas", "Río Nilo", "Río Yangtsé", "Río Misisipi")));
        preguntas.addPregunta("¿Quién escribió 'Cien años de soledad'?", 2, new ArrayList<>(List.of("Mario Vargas Llosa", "Isabel Allende", "Gabriel García Márquez", "Carlos Fuentes")));
        preguntas.addPregunta("¿Cuál es el planeta más grande del sistema solar?", 3, new ArrayList<>(List.of("Marte", "Venus", "Tierra", "Júpiter")));
        preguntas.addPregunta("¿Cuál es el animal terrestre más rápido?", 0, new ArrayList<>(List.of("Guepardo", "León", "Elefante", "Canguro")));
        preguntas.addPregunta("¿Cuál es el océano más grande del mundo?", 1, new ArrayList<>(List.of("Océano Atlántico", "Océano Pacífico", "Océano Índico", "Océano Ártico")));
        preguntas.addPregunta("¿Quién pintó 'La última cena'?", 2, new ArrayList<>(List.of("Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet")));
        preguntas.addPregunta("¿Cuál es el país más poblado del mundo?", 3, new ArrayList<>(List.of("Estados Unidos", "India", "Brasil", "China")));
        preguntas.addPregunta("¿Cuál es el ave voladora más grande del mundo?", 0, new ArrayList<>(List.of("Cóndor andino", "Águila real", "Flamenco", "Cisne")));
        preguntas.addPregunta("¿Cuál es el continente más grande del mundo?", 1, new ArrayList<>(List.of("África", "Asia", "América", "Europa")));
        preguntas.addPregunta("¿Quién es el autor de 'Don Quijote de la Mancha'?", 2, new ArrayList<>(List.of("Miguel de Unamuno", "Federico García Lorca", "Miguel de Cervantes", "Lope de Vega")));
        preguntas.addPregunta("¿Cuál es el país con más idiomas hablados?", 3, new ArrayList<>(List.of("India", "China", "Estados Unidos", "Papúa Nueva Guinea")));
        preguntas.addPregunta("¿Cuál es el mamífero más grande del mundo?", 0, new ArrayList<>(List.of("Ballena azul", "Elefante africano", "Oso polar", "Hipopótamo")));
        preguntas.addPregunta("¿Cuál es la montaña más alta del mundo?", 1, new ArrayList<>(List.of("K2", "Monte Everest", "Kangchenjunga", "Lhotse")));
        preguntas.addPregunta("¿Quién compuso la 'Novena Sinfonía'?", 2, new ArrayList<>(List.of("Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Ludwig van Beethoven", "Franz Schubert")));
        preguntas.addPregunta("¿Cuál es el desierto más grande del mundo?", 3, new ArrayList<>(List.of("Desierto del Sahara", "Desierto de Atacama", "Desierto de Gobi", "Desierto de Antártida")));
        preguntas.addPregunta("¿Cuál es el reptil más grande del mundo?", 0, new ArrayList<>(List.of("Cocodrilo del Nilo", "Cocodrilo de agua salada", "Anaconda verde", "Pitón reticulada")));
        preguntas.addPregunta("¿Cuál es el lago más profundo del mundo?", 1, new ArrayList<>(List.of("Lago Superior", "Lago Tanganica", "Lago Baikal", "Lago Nyasa")));
        preguntas.addPregunta("¿Quién escribió 'La Odisea'?", 2, new ArrayList<>(List.of("Sófocles", "Esquilo", "Homero", "Eurípides")));
        preguntas.addPregunta("¿Cuál es el río más caudaloso del mundo?", 3, new ArrayList<>(List.of("Río Nilo", "Río Yangtsé", "Río Misisipi", "Río Amazonas")));
        
        setPreguntaIntoForm();
        
        Juego.setVisible(true);
    }//GEN-LAST:event_SeleccionarJugadorBotonMouseClicked

    private void Respuesta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Respuesta1MouseClicked
        // TODO add your handling code here:
        if (Respuesta1.isEnabled()) {
            opcion_seleccionada = 0;
            checar();
        }
    }//GEN-LAST:event_Respuesta1MouseClicked

    private void Respuesta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Respuesta2MouseClicked
        // TODO add your handling code here:
        if (Respuesta2.isEnabled()) {
            opcion_seleccionada = 1;
            checar();
        }
    }//GEN-LAST:event_Respuesta2MouseClicked

    private void Respuesta3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Respuesta3MouseClicked
        // TODO add your handling code here:
        if (Respuesta3.isEnabled()) {
            opcion_seleccionada = 2;
            checar();
        }
    }//GEN-LAST:event_Respuesta3MouseClicked

    private void Respuesta4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Respuesta4MouseClicked
        // TODO add your handling code here:
        if (Respuesta4.isEnabled()) {
            opcion_seleccionada = 3;
            checar();
        }
    }//GEN-LAST:event_Respuesta4MouseClicked

    private void JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JugarActionPerformed

    private void SiguientePreguntaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SiguientePreguntaMouseClicked
        // TODO add your handling code here:
        if (SiguientePregunta.isEnabled()) {
            if (preguntas.getPreguntasRespondidas() < 10) {
                setPreguntaIntoForm();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Juego Terminado");
                usuarios.editUser(usuario_seleccionado.getId(), usuario_seleccionado);
                this.setVisible(true);
                Juego.setVisible(false);
            }
        }
    }//GEN-LAST:event_SiguientePreguntaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF: " + ex);
            
            try {
                FlatLightLaf.setup();
            } catch (Exception ex2) {
                System.err.println("Failed to initialize LaF: " + ex2);
            }
        }

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */ /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField Id;
    private javax.swing.JFrame Juego;
    private javax.swing.JLabel JugadorLabel;
    private javax.swing.JButton Jugar;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton Respuesta1;
    private javax.swing.JButton Respuesta2;
    private javax.swing.JButton Respuesta3;
    private javax.swing.JButton Respuesta4;
    private javax.swing.JLabel ResultadoDeLaPregunta;
    private javax.swing.JLabel SaldoLabel;
    private javax.swing.JButton Salir;
    private javax.swing.JFrame Seleccionador;
    private javax.swing.JButton SeleccionarJugadorBoton;
    private javax.swing.JComboBox<String> SeleccionarJugadorComboBox;
    private javax.swing.JLabel SeleccionarJugadorLabel;
    private javax.swing.JButton SiguientePregunta;
    private javax.swing.JTable Tabla;
    private javax.swing.JScrollPane TablaScroll;
    private javax.swing.JLabel TituloDeLaPregunta;
    private javax.swing.JLabel TituloDeLaVentana;
    private javax.swing.JButton Usuarios;
    private javax.swing.JFrame UsuariosFrame;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
